// <auto-generated />
using System;
using HCMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCMS.Infrastructure.Migrations
{
    [DbContext(typeof(HCMSDbContext))]
    partial class HCMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampEventGroup", b =>
                {
                    b.Property<Guid>("CampEventsCampEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CampEventsCampEventId", "GroupsGroupId");

                    b.HasIndex("GroupsGroupId");

                    b.ToTable("CampEventGroup");
                });

            modelBuilder.Entity("GroupPlayer", b =>
                {
                    b.Property<Guid>("GroupsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupsGroupId", "PlayerUserId");

                    b.HasIndex("PlayerUserId");

                    b.ToTable("GroupPlayer");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.CampEvent", b =>
                {
                    b.Property<Guid>("CampEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("CampEventId");

                    b.HasIndex("CoachId");

                    b.ToTable("CampEvents");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfMembers")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SeniorityLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GroupId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LocationCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ShiftId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.ShiftApplication", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfApply")
                        .HasColumnType("date");

                    b.Property<string>("StatusOfApplication")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlayerId", "ShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftApplications");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.TestingRecord", b =>
                {
                    b.Property<Guid>("TestingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BodyFatPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("JumpHeightCm")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PushUpCount")
                        .HasColumnType("int");

                    b.Property<int>("SprintTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("TestingRecordId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TestingRecords");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HomeTown")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("HCMS.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Coach", b =>
                {
                    b.HasBaseType("HCMS.Domain.Entities.User");

                    b.Property<string>("Biography")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EquipmentSize")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("EquipmentSize");

                    b.Property<string>("TeamName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TeamName");

                    b.HasDiscriminator().HasValue("Coach");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Player", b =>
                {
                    b.HasBaseType("HCMS.Domain.Entities.User");

                    b.Property<string>("EquipmentSize")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("EquipmentSize");

                    b.Property<string>("ParentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TeamName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TeamName");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("CampEventGroup", b =>
                {
                    b.HasOne("HCMS.Domain.Entities.CampEvent", null)
                        .WithMany()
                        .HasForeignKey("CampEventsCampEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCMS.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupPlayer", b =>
                {
                    b.HasOne("HCMS.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCMS.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HCMS.Domain.Entities.CampEvent", b =>
                {
                    b.HasOne("HCMS.Domain.Entities.Coach", "Coach")
                        .WithMany("CampEvents")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Group", b =>
                {
                    b.HasOne("HCMS.Domain.Entities.Shift", "Shift")
                        .WithMany("Groups")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Shift", b =>
                {
                    b.HasOne("HCMS.Domain.Entities.Season", "Season")
                        .WithMany("Shifts")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.ShiftApplication", b =>
                {
                    b.HasOne("HCMS.Domain.Entities.Player", "Player")
                        .WithMany("ShiftApplications")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCMS.Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftApplications")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.TestingRecord", b =>
                {
                    b.HasOne("HCMS.Domain.Entities.Player", "Player")
                        .WithMany("TestingRecords")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Season", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Shift", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("ShiftApplications");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Coach", b =>
                {
                    b.Navigation("CampEvents");
                });

            modelBuilder.Entity("HCMS.Domain.Entities.Player", b =>
                {
                    b.Navigation("ShiftApplications");

                    b.Navigation("TestingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
